#!/bin/bash -l
#$ -S /bin/bash
#$ -l h_rt=30:00:00
#$ -l mem=2G
#$ -N kmc
#$ -pe mpi 24
#$ -o q.output
#$ -e q.error
#$ -P Gold
#$ -A Faraday_MSM_bjm
#$ -cwd
#$ -ac allow=K
ulimit -s unlimited
ulimit -m unlimited
source /home/mmm0518/scratch/virtualenv/updated_kmc/bin/activate
python grain_cubic_pbc-4-new.py
python da.py
