results = "/home/w/jmd80/scratch/kmc_paper_data/charges_105/permittivity_{perm}/outputs.json"

all_results = expand(results, perm = ['1', '4', '7', '10', '13',
                                    '16', '19', '22', '25', '28',
                                     '50', '75', '100', '2', '65, '85'])

rule all:
  input:
    all_results

rule simulations_105:
  input:
  output:
    "/home/w/jmd80/scratch/kmc_paper_data/charges_105/permittivity_{permittivity}/outputs.json"
  run:
    shell("cd /home/w/jmd80/scratch/kmc_paper_data/charges_105/permittivity_{wildcards.permittivity} ")
    shell("python /home/w/jmd80/scratch/kmc_paper_data/analysis_105.py . /home/w/jmd80/scratch/kmc_paper_data/charges_105/permittivity_{wildcards.permittivity}/inputs.json")

